import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import LeftBar from "@/components/LeftBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Musix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <Navbar /> */}
          <div className="col-span-2">
            <LeftBar />
          </div>
          <div className="w-full col-span-6 bg-[#121212] rounded-md">
            <Navbar />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
